### ISSUE TITLE
Question: Can we pass custom converters

### ISSUE THREAD

**Issue by attiqe** [Innofactor/EfCoreJsonValueConverter#3]
Hi,

Thanks for a wonderful library, it makes job easier and clean code is a bonus. I have customer converters for some objects. How can we make use of it?

Thanks,
Attiqe

**Comment by Armarr** [comment]
Because this library uses Newtonsoft I would imagine you can use the the [JsonConverterAttribute ](https://www.newtonsoft.com/json/help/html/JsonConverterAttributeClass.htm)for this.

**Comment by attiqe** [comment]
@Armarr that's not what I was asking, I know that we can do with it [Value Conversions](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions), following is an example of using it in an entity configuration file:

```c#
entity
       .Property(s => s.OutstandingMatters)
       .HasColumnType(Constants.DataType.JsonType)
       .HasConversion(
             v => JsonConvert.SerializeObject(v),
             s => JsonConvert.DeserializeObject<List<User>>(s, new UserConverter()));
```

I wanted to know about the usage of the `HasJsonValueConversion `for custom converters.

**Comment by AlexEngblom** [comment]
Since HasJsonValueConversion is effectively just  wrapping Newtonsoft JsonConvert.se-/deserialize calls, I suppose @Armarr suggestion using JsonConverterAttribute should work for passing custom converters on your entities. I'll let you know when I have time to try it out.
 
Other than that there's no way of passing a converter directly for property at the moment.

**Comment by AlexEngblom** [comment]
Using [JsonConverter] attribute to pass custom converters works fine. Created an unit test showcasing their usage: caadae68308cd8a2a7b72044efde7ddb21410599
